version: '3'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    env_file:
      - ./.env
    ports:
      - '3306:3306'
    volumes:
      - cbaapp:/var/lib/mysql
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
  redis:
    container_name: redis
    image: redis:latest
    command: redis-server --port 6379
    ports:
      - 6379:6379
volumes:
  cbaapp:
