version: '3.3'
services:
  redis:
    container_name: redis
    image: redis:latest
    networks:
      - ws_proxy
    command: redis-server --port 6379
    ports:
      - 6379:6379
  was:
    container_name: was
    networks:
      - ws_proxy
    volumes:
      - ./:/app
    build:
      dockerfile: ./dockerfile.prod
    ports:
      - "8001:8001"
    env_file:
      - .env
    restart: always
volumes:
  cbaapp:

networks:
  ws_proxy:
    external: true
